plugins {
    id 'java'
}

group = 'net.hackcraft'
version = '1.0-SNAPSHOT'

java {
  toolchain {
    languageVersion.set(JavaLanguageVersion.of(21))
  }
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
            exclude '**/main/**'
        }
    }

    sampleTest {
        java {
            srcDir 'src/test/java'
        }
        resources {
            srcDir 'src/test/resources'
        }
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.main.output
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.main.output
  }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'

    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

task sampleTest(type: JavaExec) {
    classpath = sourceSets.sampleTest.runtimeClasspath
    mainClass = 'main.Main'  // Replace with the actual fully qualified name of your Main class
}

task showMeCache doLast() {
    configurations.compileClasspath.each { println it }
}
